version: "3.8"

services:
    mysql:
        image: mysql:8.3.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: nodeload
        ports:
            - "3306:3306"

    redis:
        image: redis:7.2.4
        restart: always
        ports:
            - "6379:6379"

    zookeeper:
        image: "bitnami/zookeeper:3.8-debian-10"
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        restart: always

    kafka:
        image: "bitnami/kafka:3.1-debian-10"
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper
        restart: always

    minio:
        image: minio/minio:latest
        ports:
            - "9000:9000"
            - "9001:9001"
        command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
        environment:
            - MINIO_ROOT_USER=ROOTUSER
            - MINIO_ROOT_PASSWORD=CHANGEME123
        restart: always
